name: 'Configuration Packager'
type: module
description: 'Enables administrators to package configuration into modules.'
package: Configuration
core: 8.x
configure: config_packager.export
dependencies:
  - config
  - config_devel
